init descripcion curso programar, faltan links a python/R inscripciones
MetaDocencia/SitioWeb pull request #45
Opened 2021-02-24 23:11 UTC by violetr

Acá va una primera versión de la descripción del curso basado en lo que había en el doc y la plantilla de los cursos anteriores. Linkea a learner personas (Aurora, etc) del pull request.

2021-02-27 20:25 UTC, paocorrales requested changes

2021-02-27 20:25 UTC, paocorrales commented on content/es/curso/programar/index.md
> +- Para inscribirte en la versión con ejemplos en Python puedes inscribirte acá.
```suggestion
Para pre-inscribirte en este curso, por favor completá tu mail en el formulario de abajo con el mismo mail que usaste para registrarte.

<iframe 
  src=https://script.google.com/macros/s/AKfycbyWCniyQJj13oMrYzP2I54syH4IPlo0I0PNgs324JKIeR_L-muWvO07Ww/exec"
  frameBorder="0",
  title = "Formulario de pre-inscripción",
  width="100%",
  height = 300px,
  vertical-align="text-top">
  Explorador no compatible.
</iframe> 

(Si el formulario no aparece, es posible que tengas algún bloqueador de contenido instalado. En ese caso podés ir a [este link](https://script.google.com/macros/s/AKfycbyWCniyQJj13oMrYzP2I54syH4IPlo0I0PNgs324JKIeR_L-muWvO07Ww/exec))

En cuanto abramos vacantes te vamos a mandar un mail de invitación para que elijas el día y horario que más te convenga y tendrías la posibilidad de realizar el curso con ejemplos de R o Python (según la disponibilidad).

```

2021-02-27 20:25 UTC, paocorrales commented on content/es/curso/programar/index.md
> +- Para inscribirte en la versión con ejemplos en R puedes inscribirte acá.
```suggestion

```

2021-02-27 20:25 UTC, paocorrales commented on content/es/curso/programar/index.md
> +En cuanto abramos vacantes te vamos a mandar un correo electrónico de invitación para que elijas el día y horario que más te convenga dentro de los disponibles.
```suggestion

```

2021-03-03 03:33 UTC, NPalopoli commented on content/es/curso/programar/index.md
> +Pensamos en Aurora, Patricio y Rene como [personas tipo](/personas/) al diseñar los contenidos de este taller.
René

2021-03-03 03:33 UTC, NPalopoli commented on content/es/curso/programar/index.md
> +* Patricio Python programa en Python profesionalmente desde hace quince años. Este año empezará capacitaciones internas para su empresa, sumado a las clases de programación que dicta en un instituto
Le sacaría el apellido Python

2021-03-03 09:07 UTC, violetr commented
ahí incluí comentarios de Nico

2021-03-05 15:27 UTC, merged